### PR TITLE
Add a separate Save, Close & Add button to the "create a new field" link on the templates page.

### PR DESCRIPTION
**Pull request by adrianbj**
This allows for full configuration of fields that require more than two saves, such as FieldtypeOptions.

### CODE REVIEW

**Comment by adrianbj** [comment]
To clarify, this is for the "create a new field" link on the templates page. The previous behavior meant that the modal dialog was always closed and the field added to the template on the second save, but this was problematic for fields that required three saves to be fully configured, such as FieldtypeOptions. Now you can save as many times as you want using the standard save button. The new "Save, Close & Add" button won't appear until after the first save so that the field is at least saved and ready for adding to the template.

**Comment by adrianbj** [comment]
This needs a tweak still - will make a correction and update tomorrow.

**Comment by adrianbj** [comment]
Actually, it wasn't that complicated :) I think the new behavior of just being Close & Add is much better and avoids several issues.

This way you can save as often as you want and you'll always see any messages from the fieldtype that appear after saving. Then when you have it fully configured, just click "Close & Add".

Sorry for the constant updates :)

**Comment by adrianbj** [comment]
For cross reference, this PR fixes this issue: https://github.com/processwire/processwire-issues/issues/16

**Comment by LostKobrakai** [comment]
I'm wondering how many fieldtypes really need that additional save vs. how many do not. Wouldn't this add overhead to e.g. adding a new simple text field?

**Comment by adrianbj** [comment]
> I'm wondering how many fieldtypes really need that additional save vs. how many do not. Wouldn't this add overhead to e.g. adding a new simple text field?

Potentially there is one more click if you want to add a label, textformatter, or change the visibility, but I think it is a worthwhile trade-off for the clarity that this new approach brings. With the existing way you are stuck if you need to make further changes after the second save - you have to go the field to edit it further. This can be even worse if the Setup > Fields submenu is already cached as the new file won't appear in there without a page reload. Now you need to be careful to remember to save the addition(s) to the template, or make sure to open the main Setup > Fields page in a new tab so you can access the new field to make those edits to it.

That said, I'd love if you gave the new version a test run to see if you can think of any improvements. Obviously the new button could also do a final save before closing and adding, but I currently still like the separation, although I am certainly open to feedback on this.

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I'm trying to be more official with this new PW3 repo and would like to try out our new PR process and a direct pull and merge. Please see here for the new contributing/PR guidelines: https://github.com/processwire/processwire/blob/master/CONTRIBUTING.md#pull-requests-prs
I think you are already all set with everything there, except for bullet point 2 regarding the CLA. Let me know if that works for you? Thanks. Also CC @LostKobrakai since I know he's got pending PRs in here too.

**Comment by adrianbj** [comment]
Hi @ryancramerdesign - no problem, I've signed it. You may have already come across this, but in case not, this might be of interest: https://www.clahub.com/

**Comment by adrianbj** [comment]
Actually, there may be one other issue with my PR - I did base it off the master rather than dev branch (which didn't exist then). Do you want me to close this one and submit again off the dev branch?

**Comment by ryancramerdesign** [comment]
Nope, no need as the dev branch is basically identical... just testing
things out. :)

**Comment by LostKobrakai** [comment]
@adrianbj Sorry for highjacking, but I was curious and build something like clahub, which @ryan could simply integrate into processwire.com: https://github.com/LostKobrakai/CLAServer. It's actually quite straight forward. Maybe it could try to test if there are multiple commiters in the pr history, but checking the pr opener should be enough for now.

**Comment by ryancramerdesign** [comment]
Looks like it worked. At least the code now appears on the dev branch. But this PR is still asking me to merge and not showing anything about it other than my manual commit *after* the merge to fix some minor things. It also doesn't show you as a contributor, so not sure what I missed here. Maybe it does this once merged to master branch? I just figured I should keep PRs in the dev branch to test for a few days before merging to master.

**Comment by ryancramerdesign** [comment]
@LostKobrakai I looked into both clahub and claserver, but figured we were small enough that it would be just overhead. Maybe at some point down the road that will save time, but for now I think what we've got works well.

**Comment by ryancramerdesign** [comment]
Closing this since the PR has been added, but of course the conversation continues.

**Comment by LostKobrakai** [comment]
I'm not sure if Github can detect locally merged pr's. And teh collaborators chart is probably only generated from the master branch.

**Comment by adrianbj** [comment]
I am not sure about this either - when I have submitted PRs to other projects, it has shown me as the sole committer of the code, or it has shown me "committed with" and then the maintainer of the project (with both our avatars). However, I think in all cases I have always submitted PRs against the master branch, so maybe that is the difference, but it does seem weird. Maybe it's simply because my PR was to the master branch but you committed to the dev branch so github didn't consider it a direct pull of my code changes?

Let me know if you want me to do a PR to the dev branch instead - I could do it with my original version or your modified code.

**Comment by LostKobrakai** [comment]
The master branch is only important for most of the graph type stats. Everything else should work no matter of the branch. But in this case the pr targeted master, whereas ryan did merge your branch locally against dev, which is probably the reason why github didn't pick that up. But you're still listed in the commit history.

**Comment by adrianbj** [comment]
> But you're still listed in the commit history.

True - I wonder if those commits will drive the Contributors list once the changes are pushed to master. I think most probably it will.

Among other things, this link explains that contributions are only counted for the master branch.
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by ryancramerdesign** [comment]
It doesn't seem like a good practice to merge directly to the master branch, at least not for a fairly big project like this. The approach I was using is to merge to a new branch just for the PR, test it out and make any changes, then merge to dev. The dev branch would contain various updates and PRs, which would then be merged to master after a period of testing. This seems like a good/safe way to go doesn't it? But in this new repo I'd really like to be able to show an active contributors list. I'm hoping it'll update once PRs are merged from dev to master.

**Comment by LostKobrakai** [comment]
That's certainly a save approach, but most projects simply merged via github into the dev branch. Any necessary cleanup can simply come afterwards. 

I think if you want to keep the "extra branch" workflow it could simply work like this:

- Create new `pr/xy` branch, merge and test
- Decide if you want to clean it up on your own, or leave that for the pr opener to do
- If it's ready to be merged: Accept the pr here on Github.

Only if additional cleanup was necessary on your side:
- Run git fetch on your local `dev` branch
- Rebase `pr/xy` on your local `dev` branch
- (Fast-forward) merge your local `pr/xy` into the local `dev`
- Push the clean-up

**Comment by LostKobrakai** [comment]
Ok, scratch my prev. post if github does detect merges for pr's pointing to the dev branch :)

**Comment by teppokoivula** [comment]
If you haven't yet seen it, I'd suggest taking a closer look at [a succesful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/). One thing I'd suggest copying from there would be feature branches, which would allow you / us to test a specific feature without compromising the whole dev branch *or* having to jump through any weird and awkward hoops.

A slightly less sophisticated approach has been in use at the [UserGroups repository](https://github.com/apeisa/UserGroups/branches), where feature branches have been merged directly to master and there's no separate dev branch. Works just fine for smaller codebases, but not so well for our case, where we need the concept of "releases".

As far as I know, GitHub updates the contributors list just fine once you've merged all that stuff to master. If it doesn't, it's just plain broken :)

**Comment by ryancramerdesign** [comment]
Teppo, this is actually what I've been doing– merging to a new branch just
for the feature, testing/adjusting, and then merging it to dev once
confirmed working well. So far the feature branches have only been needed
for a few minutes, so no need to push them to GitHub, but if we work on
something major that needs time or people then no doubt we'll push the
branch to GitHub too.

**Comment by teppokoivula** [comment]
Thanks for the explanation, Ryan. Makes sense to me. In fact it's quite enough for me to know that you're considering feature branches for bigger / more influential changes :)

**Pull request closed without merging**
