### PR TITLE
add button to close all notifications at once

### PR DESCRIPTION
**Pull request by BernhardBaumrock**
Hey Ryan, this is an old issue dating back to 2014: https://processwire.com/talk/topic/8329-how-to-closedelete-notifications/

I always get lots of - persistent - notifications after login:

img

I need to close every single one of them. This PR adds an additional X to close all at once:

image

Note that I've only updated the unminified JS

### CODE REVIEW

**Comment by BernhardBaumrock** [comment]
Hey @ryancramerdesign I get now what you were talking about:

img

There seems to be different logics for showing notifications in different places. I'm talking about the notifications that pop up when the systemNotifications module is installed after logging in or after refreshing modules.

The screenshot above is taken after a page was saved. There it is possible to close all notifications at once.

**Comment by BernhardBaumrock** [comment]
turns out that there are some inconsistencies between the regular notifications and the ones coming from SystemNotifications module: https://github.com/processwire/processwire-issues/issues/1554

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock I see, I didn't catch you were using the SystemNotifications module at first. This is a pretty old module that I've been thinking we'll remove from the core, as I don't think it really belongs in the core anymore. I thought it might evolve better in its own repo, as I think it's still a good module, but too much in the core, as notifications are now the purview of the admin themes.  A lot of what it does was built to the needs of the company that sponsored it, but for most I think it's better to leave presentation of notifications to the admin theme. At this time the SystemNotifications module was written, we didn't have an AdminTheme framework like we do now.

**Comment by BernhardBaumrock** [comment]
Thx @ryancramerdesign that is an interesting information! The reason why I have installed this module is to get at least some kind of warning if another user is editing the same page at the same time. Sounds like this is not a good option any more.

I prefer the default look and behaviour of notifications anyhow, so I'd be happy to remove the module. The only thing that I really need is the notification about same page editing. Maybe this feature could be built into the core as a lightweight alternative to the pro activity module?

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Do you have the UserActivity module? This is the best one for preventing page edit collisions, and it also highlights pages being edited before you even click to edit them. It's a really useful module, I might have to add it to the core.

**Comment by BernhardBaumrock** [comment]
Hey Ryan, seems I forgot that I have bought ProDevTools :D That means I'll install the UserActivity module instead of the SystemNotifications. I'll close this PR as the SystemNotifications module seems obsolete...

Having UserActivity in the core would be awesome!! I think this is something that every site could really benefit from. That's always one of the CONS I have to admit when showing ProcessWire to someone: "Oh, yes, you need to be careful not to overwrite changes that someone else did at the same time... ProcessWire does not warn you in such situations..."

**Pull request closed without merging**
