### PR TITLE
Make InputfieldSelector properly respect "allowSystemTemplates" setting.

### PR DESCRIPTION
**Pull request by adrianbj**

### CODE REVIEW

**Comment by adrianbj** [comment]
AJAX calls (eg after selecting "Template" from first dropdown) were calling the `setup()` method before the settings were populated.

**Comment by adrianbj** [comment]
@ryancramerdesign - do you want Issues created to draw attention to PRs that are bug fixes?

**Comment by ryancramerdesign** [comment]
Thanks Adrian, it looks like this one has been added.

**Comment by adrianbj** [comment]
Hey Ryan - what do you mean by "**it looks like** this one has been added"? I didn't add `$this->setup();` - I simply moved it's location. If I look at the current dev branch, it's still in the old location which means it won't work. Maybe you have already changed in your local copy, but just wanted to make sure you understood what I actually did here and why it now works, but didn't before.

I know it's a simple line change, but it actually took quite a while to figure out why the InputfieldSelector wasn't respecting the "allowSystemTemplates" option.

**Comment by adrianbj** [comment]
Hi @ryancramerdesign - I just checked the dev commit from today and `$this->setup();` is still on the wrong line and so still won't work. I don't want to hassle, but now that this PR has been closed (and I don't have the option to re-open it) I am worried it will be forgotten.

**Comment by adrianbj** [comment]
@ryancramerdesign  - just checked 3.0.59 and it's still in the wrong spot. I was I could reopen this PR. I guess I'll submit an Issue report to bring this to your attention again :)

**Pull request closed without merging**
