### PR TITLE
LazyCron improvements (support cron-style hooks)

### PR DESCRIPTION
**Pull request by MrSnoozles**
This adds 2 improvements to Lazycron.

## 1. Option to execute cron function from server only
Sometimes the cron functions are rather time consuming, like doing backups or doing some cleanup tasks. That's why I think it's good to have an option to never have it executed by website visitors.
Right now I solved it by adding a config variable `$config->lazyCronQueryParam` (the name is subject to change). If it's set LazyCron will only be executed if a query parameter (with the name specified in the configuration) is present.

Example: 
in config.php
`$config->lazyCronQueryParam = 'executeCron';`

in server config, schedule cron job to execute once per minute:
`wget --quiet --no-cache -O - http://www.your-site.com?executeCron=1 > /dev/null`

## 2. Option to hook `Lazycron::cron(* * * * *)`
With the previous LazyCron implementation it's not possible to execute something early in the morning. It's possible to tell it to be executed once a day, but we don't have an option to specify when that should be. This update solves that, by allowing to specify a cron pattern. (https://crontab.guru/ helps a lot with writing and testing patterns)

Meaning you can now write `wire()->addHook('LazyCron::cron(0 1 * * *)', null, 'myFunc')` and that will schedule to 1am sharp every day. 

The module calculates when the next runtime for that pattern should be.  If the current time is >= that time, it gets executed. It keeps track of last execution times by adding a line in the form of `<pattern>:<lastExecutionTimestamp>` in the cache file.
The important method here is `getNextCronRuntime`. I wrote a couple of tests to confirm it works correctly.

**-----TEST CASES----**
~~~php
/**
 * Run a bunch of tests to confirm that the getNextCronRuntime method works correctly
 */ 
function testGetNextCronRuntime() {
    // test with start of the day given
    $lastRuntime = strtotime('2020-04-23 00:00:00');
    $tests = array(
        '* * * * *'            => '2020-04-23 00:01:00',
        '5 4 * * *'            => '2020-04-23 04:05:00',
        '5 0 * 8 *'            => '2020-08-01 00:05:00',
        '15 14 1 * *'          => '2020-05-01 14:15:00',
        '* * * * 0'            => '2020-04-26 00:00:00',
        '0 22 * * 1-5'         => '2020-04-23 22:00:00',
        '21-55/2 * * * *'      => '2020-04-23 00:21:00',
        '23 2-20/2 * * *'      => '2020-04-23 02:23:00',
        //'5 4 * * sun'         => '2020-04-26 04:05:00',
        '0 0,12 1 */2 *'       => '2020-05-01 00:00:00',
        '0 4 8-14 * *'         => '2020-05-08 04:00:00',
        //'@weekly'             => '2020-04-26 00:00:00',
        '23 12-20/2 * 3,4,5 *' => '2020-04-23 12:23:00',
    );
    runTests($tests, $lastRuntime);

    // test with end of the day given
    $lastRuntime = strtotime('2020-04-23 23:50:00');
    $tests = array(
        '* * * * *'       => '2020-04-23 23:51:00',
        '15 14 1 * *'     => '2020-05-01 14:15:00',
        '0 22 * * 1-5'    => '2020-04-24 22:00:00',
        '23 0-20/2 * * *' => '2020-04-24 00:23:00',
        '0 0,12 1 */2 *'  => '2020-05-01 00:00:00',
        '0 0 1,15 * 3'    => '2020-04-29 00:00:00',
    );
    runTests($tests, $lastRuntime);

    // test with end of the year given
    $lastRuntime = strtotime('2019-12-30 23:50:00');
    $tests = array(
        '* * * * *'       => '2019-12-30 23:51:00',
        '15 * 1 * *'     => '2020-01-01 00:15:00',
        '* * * * 4-5'    => '2020-01-02 00:00:00',
    );
    runTests($tests, $lastRuntime);

    // tests with seconds given
    $lastRuntime = strtotime('2020-08-31 23:50:59');
    $tests = array(
        '* * * * *'       => '2020-08-31 23:51:00',
        '15 * * * *'     => '2020-09-01 00:15:00',
        '15 * * 10 *'    => '2020-10-01 00:15:00',
    );
    runTests($tests, $lastRuntime);
}


/**
 * Tests the expected outcome for an array of patterns
 * @param array $tests
 * @param int $lastRuntime
 * @throws WireException
 * @throws WirePermissionException
 */
function runTests($tests, $lastRuntime) {
    $lazycron = wire('modules')->get('LazyCron');

    foreach ($tests as $pattern => $expectedResult) {
        $result = date('Y-m-d H:i:s', $lazycron->getNextCronRuntime($pattern, $lastRuntime));
        echo sprintf('%s [%s] [%s]<br>', $pattern, $expectedResult, $result);

        if(!assert($result === $expectedResult)) {
            $message = sprintf('LazyCron: Expected result (%s) does not equal actual result (%s) for pattern "%s"',
                               $expectedResult,
                               $result,
                               $pattern
            );
            throw new \Exception($message);
        }
    }
}
~~~

Then run the tests using
~~~php
testGetNextCronRuntime();
~~~

### CODE REVIEW

**Comment by MrSnoozles** [comment]
I started working on the `master` branch so I'm now missing the changes from the dev branch. Will update this PR soon.

**Comment by MrSnoozles** [comment]
**Consideration / possible improvements:**
- an entry is written into LazyCron.cache the first time a pattern is used. When the hook for that pattern is removed, the last executed timestamp will not get refreshed. That means if a user defines a pattern for "on the first of the month", removes it and adds it again a year later it would get executed immediately. I think that's okay but it's something to consider
- Instead of calculating the next execution time every time it would probably be smarter to save them in the LazyCron.cache file too. So each line would consist of `<pattern>:<lastExecuted>:<nextExecution>`

**Comment by ryancramerdesign** [comment]
@MrSnoozles Thanks, this looks great. I'd like to add something like item 1 for sure. Item 2 also looks really useful, and I like the way you've put it all together, nicely done. Currently it's a little more functionality and code than I want to maintain with this module in the core, as I'd like to keep LazyCron really basic for simple needs (and likewise simple to maintain). My hope was that someone would make something better for more demanding use cases, and it looks like you've done that. I was wondering if you would consider instead maintaining this in a module in the directory (LazyCronPlus? UnlazyCron? WokeCron?), perhaps one that extends LazyCron (or not). We could point people to your module for when they need more. If you would like I could assist in getting it started?

**Comment by MrSnoozles** [comment]
Hi @ryancramerdesign . Thanks for the feedback. 

> I like the way you've put it all together, nicely done
Always happy to read compliments :)

Yes, I can put it in a module too. Would love to keep the `wire()->addHook('LazyCron::cron(0 1 * * *)'` syntax, but that should be possible even from a module. I guess I'll figure it out. I'll let you know when it's published, would be great to have it referenced in the LazyCron documentation.

**Comment by ryancramerdesign** [comment]
@MrSnoozles Great, sounds good. In the case of a new module, hooks you use would just be to the name of the module rather than LazyCron, i.e. `HappyCron::method(...)`. Though I'm not sure that syntax is something that ProcessWire hooks will recognize and pass through where you want it to, but if you found it was working before it should still work. Let me know if I can be of any help.

**Pull request closed without merging**
