### PR TITLE
Prevent FOUC showing debug mode content when page loads in Reno theme.

### PR DESCRIPTION
**Pull request by adrianbj**

### CODE REVIEW

**Comment by adrianbj** [comment]
This just implements the same code used in the default theme: https://github.com/processwire/processwire/blob/2d9e959bf2f773a207b9b0a8fa274d0f199fe127/wire/modules/AdminTheme/AdminThemeDefault/styles/sass/main.scss#L323-L325

**Comment by ryancramerdesign** [comment]
@adrianbj I'm not sure if this one is still applicable or already fixed, but if you find it is still applicable, how do I see the FOUC that it fixes? Right now I'm not seeing an FOUC in Reno, though maybe I'm not in the right place to see it. If the fix is necessary I just want to make sure I can conform it works after applying it. Thanks.

**Comment by adrianbj** [comment]
@ryancramerdesign - I just installed the Reno theme for the first time in years :)

Looks like it's no longer an issue because the debug mode content is now is a panel, rather than being displayed at the bottom of the page - that is where it used to FOUC.

**Comment by ryancramerdesign** [comment]
Okay sounds good, thanks!

**Pull request closed without merging**
