### PR TITLE
triggers on revealing and hiding fields (showIf)

### PR DESCRIPTION
**Pull request by rolandtoth**

### CODE REVIEW

**Comment by ryancramerdesign** [comment]
Thanks @rolandtoth this PR has been added in the referenced commit.

**Comment by rolandtoth** [comment]
Thanks! One issue though: `showInputfield `doesn't include the second parameter (`$fieldToShow`, like `hideInputfield `does).

https://github.com/processwire/processwire/blob/d4d90a53fe513ca923d30fce5ffa4469c8034da8/wire/templates-admin/scripts/inputfields.js#L440

https://github.com/processwire/processwire/blob/d4d90a53fe513ca923d30fce5ffa4469c8034da8/wire/templates-admin/scripts/inputfields.js#L451

Or is there other way to get the inputfield that was shown or hidden?

**Comment by ryancramerdesign** [comment]
Oops, my mistake. Fixed–thanks.

**Comment by rolandtoth** [comment]
Looks fine to me, thanks! :)

**Pull request closed without merging**
