### PR TITLE
Add hookable method to PageImage variation creation

### PR DESCRIPTION
**Pull request by karltdev**
Reference request: [https://github.com/processwire/processwire-requests/issues/223](https://github.com/processwire/processwire-requests/issues/223)

### CODE REVIEW

**Comment by ryancramerdesign** [comment]
@karltdev Sounds like this would be worthwhile to add, but since the added method doesn't actually create a variation, I'm wondering if we would be better off with a hookable method named `___createdVariation()` (past tense) that is called after the variation has been created and renamed? ... Or a hookable method named `___createVariationReady()` that is called before the variation is created? (i.e. before the resize method is called?)

**Comment by matjazpotocnik** [comment]
@karltdev, thoughts on Ryan's comments?

**Comment by karltdev** [comment]
I agree with the name ___createdVariation()

**Comment by ryancramerdesign** [comment]
Thanks @karltdev this has been added.

**Comment by matjazpotocnik** [comment]
@karltdev can you close this PR?

**Pull request closed without merging**
